api:
  # Listening IP; 0.0.0.0 means both internal and external IPs are listened to, default is recommended
  listenIP: 127.0.0.1
  # Listening ports; if multiple are configured, multiple instances will be launched
  ports: [ 10013 ]
  # API compression level; 0: default compression, 1: best compression, 2: best speed, -1: no compression
  compressionLevel: 0

prometheus:
  enable: true
  autoSetPorts: true
  ports: [ 12002 ]
  grafanaURL: http://127.0.0.1:13000/
