enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ localhost:12379 ]
  username: ''
  password: ''

kubernetes:
  namespace: default

rpcService:
  discover: discover-rpc-service
  admin: admin-rpc-service
